apiVersion: v1
kind: Secret
metadata:
  name: {{ template "consul.fullname" . }}-server
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "consul.name" . }}
    chart: {{ template "consul.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  {{- if .Values.global.gossipEncryption.secret }}
  gossip-key: {{ .Values.global.gossipEncryption.secret | b64enc | quote }}
  {{- end }}